version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: mezzo   
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - illumos
    id: mezzo
    main: ./cmd/mezzo

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-{{.Version}}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

kos:
  - repositories:
      - foundry.fsky.io/fsky/mezzo
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: none
    labels:
      org.opencontainers.image.authors: FSKY
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.description: A private and lightweight GIF viewer for Tenor
      org.opencontainers.image.licenses: AGPL-3.0-or-later
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.source: https://foundry.fsky.io/fsky/mezzo
      org.opencontainers.image.title: Mezzo
      org.opencontainers.image.url: https://mezzo.fsky.io/
      org.opencontainers.image.vendor: FSKY
      org.opencontainers.image.version: "{{.Version}}"

gitea_urls:
  api: https://foundry.fsky.io/api/v1
  download: https://foundry.fsky.io

release:
  gitea:
    owner: fsky
    name: mezzo
  name_template: "Mezzo v{{.Version}}"
  disable: false
  mode: append
