services:
  mezzo:
    image: foundry.fsky.io/fsky/mezzo:latest
    restart: always
    container_name: "mezzo"
    ports:
      - 8006:8006 # Specify `127.0.0.1:8006:8006` instead if using a reverse proxy
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    #environment:
    # - MEZZO_PORT=8006
    # - MEZZO_PATCHES_URL=
    # - MEZZO_CACHE_DISABLED=false
    # - MEZZO_CACHE_GIF_TTL=1h
    # - MEZZO_CACHE_GIF_MAX=1000
    # - MEZZO_CACHE_SEARCH_TTL=10m
    # - MEZZO_CACHE_SEARCH_MAX=500
    # - MEZZO_CACHE_PROFILE_TTL=30m
    # - MEZZO_CACHE_PROFILE_MAX=200
